"""add chunk embeddings

Revision ID: 175f15a4bf3c
Revises: fbe42262eb18
Create Date: 2026-09-24 12:49:27.979336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175f15a4bf3c'
down_revision: Union[str, Sequence[str], None] = 'fbe42262eb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chunk_embedding_model', 'chunk_embeddings', ['chunk_id', 'model_name', 'model_version'])
    op.alter_column('document_versions', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_versions', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_constraint('uq_chunk_embedding_model', 'chunk_embeddings', type_='unique')
    # ### end Alembic commands ###
