"""add document processing state

Revision ID: 20874edba476
Revises: 7305e06292df
Create Date: 2026-09-22 12:20:03.175180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20874edba476'
down_revision: Union[str, Sequence[str], None] = '7305e06292df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('processing_status', sa.String(length=32), nullable=True))
    op.add_column('document_versions', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('document_versions', sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'processing_error')
    op.drop_column('document_versions', 'extracted_text')
    op.drop_column('document_versions', 'processing_status')
    # ### end Alembic commands ###
