"""add knowledge graph tables

Revision ID: 88e38008b930
Revises: ecce8b801d1d
Create Date: 2026-09-30 20:52:51.626372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e38008b930'
down_revision: Union[str, Sequence[str], None] = 'ecce8b801d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canonical_name', 'entity_type', name='uq_entity_tenant_name_type')
    )
    op.create_index(op.f('ix_entities_tenant_id'), 'entities', ['tenant_id'], unique=False)
    op.create_table('entity_mentions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('mention_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'chunk_id', 'mention_text', name='uq_entity_mention')
    )
    op.create_index(op.f('ix_entity_mentions_chunk_id'), 'entity_mentions', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_entity_id'), 'entity_mentions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_tenant_id'), 'entity_mentions', ['tenant_id'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_entity_id', 'target_entity_id', 'relationship_type', 'source_chunk_id', name='uq_entity_relationship')
    )
    op.create_index(op.f('ix_entity_relationships_source_chunk_id'), 'entity_relationships', ['source_chunk_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_source_entity_id'), 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_target_entity_id'), 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relationships_tenant_id'), 'entity_relationships', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_document_chunks_search_vector'), table_name='document_chunks', postgresql_using='gin')
    op.alter_column('document_versions', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_versions', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.create_index(op.f('ix_document_chunks_search_vector'), 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_entity_relationships_tenant_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_target_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_entity_id'), table_name='entity_relationships')
    op.drop_index(op.f('ix_entity_relationships_source_chunk_id'), table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_entity_mentions_tenant_id'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_entity_id'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_chunk_id'), table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_index(op.f('ix_entities_tenant_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
