"""add data source access

Revision ID: 901a6096c9df
Revises: 88e38008b930
Create Date: 2026-10-02 10:20:16.074679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901a6096c9df'
down_revision: Union[str, Sequence[str], None] = '88e38008b930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'data_source_id', name='uq_data_source_access')
    )
    op.create_index(op.f('ix_data_source_access_data_source_id'), 'data_source_access', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_data_source_access_tenant_id'), 'data_source_access', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_data_source_access_user_id'), 'data_source_access', ['user_id'], unique=False)
    op.alter_column('document_versions', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_versions', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_index(op.f('ix_data_source_access_user_id'), table_name='data_source_access')
    op.drop_index(op.f('ix_data_source_access_tenant_id'), table_name='data_source_access')
    op.drop_index(op.f('ix_data_source_access_data_source_id'), table_name='data_source_access')
    op.drop_table('data_source_access')
    # ### end Alembic commands ###
