"""add ingestion job retry fields

Revision ID: 9fdbadce35c6
Revises: 901a6096c9df
Create Date: 2026-10-02 15:16:24.867588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdbadce35c6'
down_revision: Union[str, Sequence[str], None] = '901a6096c9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_versions', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.add_column('ingestion_jobs', sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('ingestion_jobs', sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False))
    op.add_column('ingestion_jobs', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'last_error')
    op.drop_column('ingestion_jobs', 'claimed_at')
    op.drop_column('ingestion_jobs', 'max_attempts')
    op.drop_column('ingestion_jobs', 'attempt_count')
    op.alter_column('document_versions', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
